K.clear_session()
tb_call = keras.callbacks.TensorBoard(log_dir='C:\\Users\\tkalnik\\PycharmProjects\\RIIAA_Escuela18-master\\logs\\logs', histogram_freq=0, write_graph=True, write_images=True)

model = Sequential()
model.add(Dense(units=20, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(units=20, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(units=20, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(units=25, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(units=25, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(units=25, input_dim=X_train.shape[-1], kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer="adam", metrics=['accuracy'])
print(model.summary())
model.fit(X_train, Y_train, epochs=500, batch_size=32, callbacks=[tb_call])
